
from rdkit import Chem

raw_smiles = "OC=1C=C2C([C@H]([C@H](CC2)C3=CC=CC=C3)C4=CC=C(C=C4)N5CCC(CN6CCN(CC6)C=7C=C8C(=CC7)C(=O)N(C8)[C@@H]9C(=O)NC(=O)CC9)CC5)=CC1"
mol = Chem.MolFromSmiles(raw_smiles)
canonical = Chem.MolToSmiles(mol)

# Probe: 1 sample to see if pipeline works at all
inputs_probe = {
    "name": "ARV471_ERalpha_CRBN_probe",
    "sequences": [
        {"protein": {"id": "A", "sequence": "SIKRSKKNSLALSLTADQMVSALLDAEPPILYSEYDPTRPFSEASMMGLLTNLADRELVHMINWAKRVPGFVDLTLHDQVHLLECAWLEILMIGLVWRSMEHPGKLLFAPNLLLDRNQGKCVEGMVEIFDMLLATSSRFRMMNLQGEEFVCLKSIILLNSGVYTFLSSTLKSLEEKDHIHRVLDKITDTLIHLMAKAGLTLQQQHQRLAQLLLILSHIRHMSNKGMEHLYSMKCKNVVPLSDLLLEMLDAHRLHAPTS"}},
        {"protein": {"id": "B", "sequence": "MDWSHPQFEKSAVDENLYFQGGGRMAAEEGGDGRRNMGNPPPPAPAESEEEDDNEMEVEDQDGKEAEKPNMINFDTSLPTSHMYLGSDMEEFHGRTLHDDDSCQVIPVLPHVMVMLIPGQTLPLQLFHPQEVSMVRNLIQKDRTFAVLAYSNVREREAHFGTTAEIYAYREEQEYGIETVKVKAIGRQRFKVLEIRTQSDGIQQAKVQILPERVLPSTMSAVQLQSLSRRHIFPSSKPKVWQDRAFRQWWQKYQKRKFHCASLTSWPPWLYSLYDAETLMERVKRQLHEWDENLKDESLPTNPIDFSYRVAACLPIDDALRIQLLKIGSAIQRLRCELDIMNKCTSLCCKQCQDTEITTKNEIFSLSLCGPMAAYVNPHGYIHETLTVYKACNLNLSGRPSTEHSWFPGYAWTIAQCRICGNHMGWKFTATKKDMSPQKFWGLTRSALLPRIPEAEDELGHDRSPLLCL"}},
        {"ligand": {"id": "C", "smiles": canonical}}
    ],
    "modelSeeds": [42],
    "seed": 42,
    "diffusion_samples": 1,
    "output_format": "pdb",
    "use_msa_server": False,
    "dialect": "alphafold3",
    "version": 1
}

print("Probe run: 1 diffusion sample...")
r_probe = run_aidd_tool('protacfold', inputs_probe, gpu=True)
print("rc:", r_probe.get('rc'))
print("summary:", r_probe.get('summary'))
