
# Full-length ERalpha + CRBN, but with the fast sanity-check settings
# If this works, the crash is inference memory, not DataLoader
r_full_low = run_aidd_tool('protacfold', {
    "name": "ARV471_ERalpha_CRBN_full_low",
    "sequences": [
        {"protein": {"id": "A", "sequence": "SIKRSKKNSLALSLTADQMVSALLDAEPPILYSEYDPTRPFSEASMMGLLTNLADRELVHMINWAKRVPGFVDLTLHDQVHLLECAWLEILMIGLVWRSMEHPGKLLFAPNLLLDRNQGKCVEGMVEIFDMLLATSSRFRMMNLQGEEFVCLKSIILLNSGVYTFLSSTLKSLEEKDHIHRVLDKITDTLIHLMAKAGLTLQQQHQRLAQLLLILSHIRHMSNKGMEHLYSMKCKNVVPLSDLLLEMLDAHRLHAPTS"}},
        {"protein": {"id": "B", "sequence": "MDWSHPQFEKSAVDENLYFQGGGRMAAEEGGDGRRNMGNPPPPAPAESEEEDDNEMEVEDQDGKEAEKPNMINFDTSLPTSHMYLGSDMEEFHGRTLHDDDSCQVIPVLPHVMVMLIPGQTLPLQLFHPQEVSMVRNLIQKDRTFAVLAYSNVREREAHFGTTAEIYAYREEQEYGIETVKVKAIGRQRFKVLEIRTQSDGIQQAKVQILPERVLPSTMSAVQLQSLSRRHIFPSSKPKVWQDRAFRQWWQKYQKRKFHCASLTSWPPWLYSLYDAETLMERVKRQLHEWDENLKDESLPTNPIDFSYRVAACLPIDDALRIQLLKIGSAIQRLRCELDIMNKCTSLCCKQCQDTEITTKNEIFSLSLCGPMAAYVNPHGYIHETLTVYKACNLNLSGRPSTEHSWFPGYAWTIAQCRICGNHMGWKFTATKKDMSPQKFWGLTRSALLPRIPEAEDELGHDRSPLLCL"}},
        {"ligand":  {"id": "C", "smiles": canonical}}
    ],
    "modelSeeds": [42], "seed": 42,
    "diffusion_samples": 1,
    "sampling_steps": 10,
    "recycling_steps": 1,
    "output_format": "pdb",
    "use_msa_server": False,
    "dialect": "alphafold3", "version": 1
}, gpu=True)

print("rc:", r_full_low.get('rc'))
print("summary:", r_full_low.get('summary'))
