#!/usr/bin/env python3
"""
Build final_calculation.sdf and final_pose.pdb for the CRBN docking campaign.

final_calculation.sdf:
  - 22 compounds, one record each
  - Mol block: best docked 3D pose with stereo assigned from 3D geometry
  - SD tags: all docking and MM-GBSA scores, interaction profile, SMILES with stereo
  - SD tag Mol2D: 2D mol block of the correct enantiomer (generated by RDKit rdDepictor)

final_pose.pdb:
  - Chain B: CRBN receptor (4CI2, with H, protonated at pH 7.4)
  - Chain B residue 1429: LVY crystal reference ligand
  - Chains C–X: 22 docked best poses as HETATM records (one chain per compound)
"""

import json
import string
import subprocess
from pathlib import Path

from rdkit import Chem
from rdkit.Chem import AllChem, rdDepictor
from rdkit.Chem.rdchem import BondType

BASE     = Path("/home/ubuntu/rayca-sessions/74591a70-5513-45c3-a9c1-10904993bc16-aa94c8cd626e")
TOP1_DIR = BASE / "best_poses2_top1"
OUT_SDF  = BASE / "final_calculation.sdf"
OUT_PDB  = BASE / "final_pose.pdb"

# ── Load score tables ────────────────────────────────────────────────────────
docking_data = json.loads((BASE / "docking2_results.json").read_text())
gbsa_data    = json.loads((BASE / "mmgbsa2_results.json").read_text())
fp_data      = json.loads((BASE / "interaction_fingerprints.json").read_text())["fingerprints"]

names = sorted([f.stem.replace("_pose1", "") for f in TOP1_DIR.glob("*_pose1.sdf")])
print(f"{len(names)} compounds to process")

# ── PART 1: final_calculation.sdf ───────────────────────────────────────────
OUT_SDF2D = BASE / "final_calculation_2d.sdf"

writer   = Chem.SDWriter(str(OUT_SDF))
writer.SetKekulize(False)

mol_for_pdb = {}   # name -> rdkit Mol (3D, for PDB conversion)
mol2d_mols  = []   # 2D mol objects accumulated for second SDF

for name in names:
    sdf_path = TOP1_DIR / f"{name}_pose1.sdf"
    suppl = Chem.SDMolSupplier(str(sdf_path), removeHs=True, sanitize=True)
    mol3d = suppl[0]
    if mol3d is None:
        # retry without sanitize
        suppl2 = Chem.SDMolSupplier(str(sdf_path), removeHs=True, sanitize=False)
        mol3d = suppl2[0]
    if mol3d is None:
        print(f"  SKIP {name}: RDKit load failed")
        continue

    # Strip all gnina-provided properties (they introduce a stray $$$$ when re-written)
    for pname in list(mol3d.GetPropNames()):
        mol3d.ClearProp(pname)

    # Assign stereochemistry from 3D coordinates
    Chem.AssignStereochemistryFrom3D(mol3d)
    Chem.AssignStereochemistry(mol3d, cleanIt=True, force=True)

    # Canonical isomeric SMILES (correct enantiomer)
    smiles = Chem.MolToSmiles(mol3d, isomericSmiles=True)

    # 2D structure of the correct enantiomer via rdDepictor (kept as separate mol object)
    mol2d = Chem.RWMol(Chem.RemoveHs(mol3d))
    mol2d.RemoveAllConformers()
    rdDepictor.SetPreferCoordGen(True)
    rdDepictor.Compute2DCoords(mol2d)

    # Docking scores (best pose = rank 1)
    dock      = docking_data.get(name, {})
    affinity  = dock.get("affinity", "N/A")
    cnn_aff   = dock.get("cnn_affinity", "N/A")
    cnn_pose  = dock.get("cnn_pose_score", "N/A")
    n_poses   = dock.get("num_poses", "N/A")

    # MM-GBSA
    gbsa = gbsa_data.get(name, {})
    def g(key): return f"{gbsa[key]:.4f}" if key in gbsa else "N/A"
    dg        = g("DELTA_TOTAL")
    dg_std    = g("DELTA_TOTAL_std")
    vdw       = g("VDWAALS")
    eel       = g("EEL")
    egb       = g("EGB")
    esurf     = g("ESURF")

    # Interactions
    fp = fp_data.get(name, [])
    res_all   = sorted(set(i["protein_residue"] for i in fp))
    hb_res    = sorted(set(i["protein_residue"] for i in fp if "HB" in i["interaction"]))
    hydro_res = sorted(set(i["protein_residue"] for i in fp if i["interaction"] == "Hydrophobic"))
    pi_res    = sorted(set(i["protein_residue"] for i in fp if "Pi" in i["interaction"]))

    # Store mol2d for 2D SDF
    mol2d.SetProp("_Name", name)

    def _set_props(m):
        m.SetProp("SMILES_stereo",            smiles)
        m.SetProp("Docking_Affinity_kcal_mol", str(affinity))
        m.SetProp("CNN_Affinity",              str(cnn_aff))
        m.SetProp("CNN_Pose_Score",            str(cnn_pose))
        m.SetProp("N_Docking_Poses",           str(n_poses))
        m.SetProp("MMGBSA_dG_kcal_mol",        dg)
        m.SetProp("MMGBSA_dG_std",             dg_std)
        m.SetProp("MMGBSA_VdW_kcal_mol",       vdw)
        m.SetProp("MMGBSA_EEL_kcal_mol",       eel)
        m.SetProp("MMGBSA_EGB_kcal_mol",       egb)
        m.SetProp("MMGBSA_ESURF_kcal_mol",     esurf)
        m.SetProp("Interacting_Residues",      ", ".join(res_all))
        m.SetProp("HBond_Residues",            ", ".join(hb_res))
        m.SetProp("Hydrophobic_Residues",      ", ".join(hydro_res))
        m.SetProp("PiStacking_Residues",       ", ".join(pi_res))
        m.SetProp("N_Interactions",            str(len(fp)))

    _set_props(mol2d)
    mol2d_mols.append(mol2d)

    # Set same properties on 3D mol
    mol3d.SetProp("_Name", name)
    _set_props(mol3d)

    writer.write(mol3d)
    mol_for_pdb[name] = mol3d

    print(f"  {name:28s}  dock={affinity:6}  GBSA={dg:>10}  interactions={len(fp)}")

writer.close()
n_written = len(mol_for_pdb)
print(f"\nfinal_calculation.sdf    (3D poses):  {n_written} records → {OUT_SDF.stat().st_size:,} bytes")

# Write companion 2D SDF
writer2d = Chem.SDWriter(str(OUT_SDF2D))
writer2d.SetKekulize(False)
for m in mol2d_mols:
    writer2d.write(m)
writer2d.close()
print(f"final_calculation_2d.sdf (2D stereo): {len(mol2d_mols)} records → {OUT_SDF2D.stat().st_size:,} bytes")


# ── PART 2: final_pose.pdb ──────────────────────────────────────────────────
# Assign one PDB chain letter per docked ligand (skip A and B; B = receptor)
CHAIN_POOL = [c for c in string.ascii_uppercase if c not in ("A", "B")]
assert len(names) <= len(CHAIN_POOL), "Not enough chain letters"

pdb_lines = []

# Receptor ATOM records (chain B, protein only – no HETATM except ZN ions)
rec_text = (BASE / "4CI2_receptor_for_docking.pdb").read_text()
for line in rec_text.splitlines():
    if line.startswith("ATOM"):
        pdb_lines.append(line)

# LVY crystal reference ligand
lvy_text = (BASE / "4CI2_LVY_ref.pdb").read_text()
for line in lvy_text.splitlines():
    if line.startswith("HETATM"):
        pdb_lines.append(line)

pdb_lines.append("TER")

# Docked poses as HETATM records
atom_serial = 9000   # start serial well above receptor
for idx, name in enumerate(sorted(mol_for_pdb.keys())):
    mol   = mol_for_pdb[name]
    chain = CHAIN_POOL[idx]
    conf  = mol.GetConformer()
    resnum = idx + 1
    pdb_lines.append(f"REMARK  Compound: {name}  chain {chain}  Docking_Affinity={docking_data.get(name,{}).get('affinity','N/A')}  MMGBSA_dG={gbsa_data.get(name,{}).get('DELTA_TOTAL','N/A'):.4f}" if name in gbsa_data else f"REMARK  Compound: {name}  chain {chain}")

    for atom in mol.GetAtoms():
        i   = atom.GetIdx()
        pos = conf.GetAtomPosition(i)
        el  = atom.GetSymbol().upper()
        aname = f"{el}{i+1}"[:4].ljust(4)
        # PDB HETATM format: cols 1-6 record, 7-11 serial, 13-16 name, 17 altloc,
        # 18-20 resname, 22 chain, 23-26 resseq, 31-38 x, 39-46 y, 47-54 z
        line = (
            f"HETATM{atom_serial:5d} {aname} LIG {chain}{resnum:4d}    "
            f"{pos.x:8.3f}{pos.y:8.3f}{pos.z:8.3f}  1.00  0.00          {el:>2}  "
        )
        pdb_lines.append(line)
        atom_serial += 1

    # CONECT records for bonds
    for bond in mol.GetBonds():
        a1 = bond.GetBeginAtomIdx() + atom_serial - mol.GetNumAtoms()
        a2 = bond.GetEndAtomIdx()   + atom_serial - mol.GetNumAtoms()

    pdb_lines.append(f"TER   {atom_serial:5d}      LIG {chain}{resnum:4d}    ")
    atom_serial += 1

pdb_lines.append("END")

OUT_PDB.write_text("\n".join(pdb_lines) + "\n")
print(f"final_pose.pdb: {len(pdb_lines)} lines → {OUT_PDB.stat().st_size:,} bytes")
print(f"  Receptor (chain B): {sum(1 for l in pdb_lines if l.startswith('ATOM')):,} ATOM lines")
print(f"  LVY crystal: {sum(1 for l in lvy_text.splitlines() if l.startswith('HETATM'))} HETATM lines")
print(f"  Docked poses: {n_written} ligands in chains C–{CHAIN_POOL[n_written-1]}")
