
phase1_text = """# Phase 1 — Parse HTE_Edelris_2.sdf and Inventory Reagents

## Inputs
- `/home/ubuntu/rayca-artifacts/faa585e0ffd53b0a98ea5bca/files/HTE_Edelris_2.sdf` (138 481 bytes)

## Method
RDKit `SDMolSupplier` with `removeHs=False`. Properties: MOL_NAME, CAS_NUMBER, Role
(Role blank for all 74 entries; names taken from MOL_NAME; class assigned by SMILES/MW).

## Outputs
| File | Content |
|------|---------|
| `007_chem_sdmolsupplier.py` | Parse + full 74-row table |
| `008_classify_all_74_reagents_check_acid_additives.py` | Classification + Brønsted-acid check |

## Result — 74 molecules, 0 failures

| Class | Count | Kit indices |
|-------|-------|-------------|
| Photocatalyst — Ir | 4 | 12, 31, 35, 58 |
| Photocatalyst — Ru | 3 | 13, 15, 33 |
| Photocatalyst — Organic | 5 | 5, 6, 32, 38, 60 |
| Ni catalyst | 4 | 10, 21, 34, 55 |
| Pd catalyst (not relevant) | 20 | 0,2,3,7–9,14,16–19,30,36,39,40,47,56,59,61,63 |
| Bidentate N-ligand | 8 | 1, 4, 11, 22, 26, 27, 46, 57 |
| Chiral N-ligand | 1 | 62 |
| Base (inorganic/organic) | 12 | 23,29,37,41,42,43,48,50,51,52,53,71 |
| Solvent | 11 | 24,25,64,65,66,67,68,69,70,72,73 |
| Cu catalyst | 1 | 49 |
| HAT/amine additive | 1 | 28 |
| P-Ligand | 2 | 20, 45 |

## Key findings vs. HTE_Edelris.sdf (kit 1)
- **MeCN (kit #72) ADDED** — absent from kit 1, now present ✓
- **Water (kit #73) ADDED** — new cosolvent option ✓
- **DCE (kit #68)** replaces DCM from kit 1
- **Dioxane (kit #70)** confirmed (C1COCCO1, MW 88.1)
- Duplicate DBU: rows 37 and 71 (identical SMILES, identical MW 152.2)

## Critical gap: NO Brønsted acid anywhere in the 74 entries
Automated search for free COOH and SO₃H found zero hits.
TFA is absent. This is the absolutely necessary missing reagent for the Minisci reaction.

## Audit
- len(mols2) == 74, None-count == 0
- MW range: 18.0 (Water) – 1121.9 (Ir-PC)
- SMILES round-trip clean for all 74 entries
"""

phase2_text = """# Phase 2 — Design Photocatalytic Minisci HTE Campaign + Plate Map

## Reaction identity
- **Type:** Photocatalytic NHP-ester Minisci radical C–H alkylation (no Ni required)
- **Electrophile/acceptor:** Brc1cncc2ccccc12 — bromoquinoline (radical acceptor at C2)
- **NHP ester / radical precursor:** CC(C)(C)OC(=O)N1CCC(CC1)C(=O)OC2C(=O)c3ccccc3C2=O
  (N-Boc piperidine-4-yl radical generated by reductive fragmentation + decarboxylation)
- **Product:** CC(C)(C)OC(=O)N1CCC(CC1)c2ncc(Br)c3ccccc23

## Mechanism
1. PC* + NHP-ester → PC⁺ + R• + CO₂ + phthalimide⁻  (oxidative quenching; PC* acts as reductant)
2. R• + quinolinium (protonated) → radical adduct at C2
3. Adduct radical + PC⁺ → quinolinium cation + PC (re-oxidation)
4. Deprotonation → aromatic product

**Ni is NOT required.** The Pd block (20 entries) and Ni block (4 entries) are irrelevant.

## Response
| Item | Decision |
|------|----------|
| Response | Relative conversion (%): product / (product + SM) × 100 |
| Measurement | UPLC, internal standard (1,3,5-trimethoxybenzene, 1 equiv) |
| Precision | ±3–5% absolute (HTE well-to-well handling dominates over UPLC inj-inj CV) |
| Threshold | ≥30% = hit for Round 2; ≥60% = direct optimisation candidate |

## Factors varied — all categorical

| Factor | Levels | Justification |
|--------|--------|---------------|
| **Photocatalyst** (rows) | 4 | E*(PC*/PC⁺) must exceed Ep(NHP ester) ≈ −1.0 to −1.2 V vs SCE. PC is the highest-impact variable. |
| **Solvent** (column pairs) | 3 | Controls radical solvation, NHP-ester solubility, and quinolinium pKₐ; widely varied in Minisci optimisation. |
| **Acid additive** (odd/even) | 2 | Protonation of quinoline N activates the ring toward radical addition; tested as TFA vs. no acid. |

**Photocatalyst selection (E* for oxidative quenching pathway):**
| Row | PC | E*(PC*/PC⁺) | Remark |
|-----|----|-------------|--------|
| A | fac-Ir(ppy)₃ (kit #58) | −1.51 V | Strongest reductant; reference for NHP Minisci |
| B | 4CzIPN (kit #38) | −1.04 V | Organic PC; most used in published NHP-Minisci |
| C | Ir(ppy)₂(dtbbpy)·PF₆ (kit #35) | −0.96 V | Moderate Ir; useful comparison |
| D | Ir[dF(CF₃)ppy]₂(dtbbpy)·PF₆ (kit #31) | −0.89 V | Borderline; included as low-E* reference |

**Solvents:** MeCN (kit #72), DMSO (kit #24), Dioxane (kit #70)
**Bases:** none — Minisci does not require an exogenous base; TFA provides acidity.

## Absolutely necessary missing reagent
**TFA (trifluoroacetic acid, ≥99%) — MUST PURCHASE**
No Brønsted acid is present in any of the 74 kit entries.
Use 1.0 equiv vs quinoline. Without protonation, radical addition rate and regioselectivity
to quinoline C2 drop substantially (literature precedent: >10× rate difference ± acid).

## Factors held constant
| Factor | Value | Reason |
|--------|-------|--------|
| No Ni catalyst | — | Minisci is PC-only; Ni adds cost and complexity without precedent benefit here |
| Concentration | 0.1 M | Standard HTE photocatalysis scale |
| NHP ester | 1.5 equiv | Compensates for non-productive fragmentation pathways |
| PC loading | 2 mol% | Catalytic; not rate-limiting at 470 nm |
| Temperature | rt | Standard photocatalysis; temperature is a Round 2 lever |
| Time | 16 h | Overnight; not varied until hit found |
| Light | 470 nm | Fixed by instrument |

## Design — full 4 × 3 × 2 factorial = 24 wells

**Why this design suits the factor set:**
All three factors are categorical. The product 4 × 3 × 2 = 24 exactly matches one plate,
making a full factorial achievable. Every main effect and 2-way interaction is estimable
with no sacrifice; no fractional design is needed.

**Plate layout:**
- Row A–D → Photocatalyst
- Column pairs 1–2 / 3–4 / 5–6 → Solvent (MeCN / DMSO / Dioxane)
- Odd columns (1, 3, 5) → TFA 1 equiv; even columns (2, 4, 6) → no acid

**Pre-registered model:**
Y_ijk = µ + α_i(PC) + β_j(Solv) + γ_k(Acid) + (αβ)_ij + (αγ)_ik + (βγ)_jk + ε_ijk

| Source | df |
|--------|----|
| PC | 3 |
| Solvent | 2 |
| Acid | 1 |
| PC × Solvent | 6 |
| PC × Acid | 3 |
| Solvent × Acid | 2 |
| **PC × Solv × Acid (error)** | **6** |
| **Total** | **23** |

3-way interaction (6 df) used as error surrogate (assumed negligible at screening stage).
Transform: arcsin√(p/100) if conversions cluster near 0 or 100%.

## Round structure

| Round | Plate | Variables | Decision rule |
|-------|-------|-----------|---------------|
| 1 (this plate) | 24 wells | PC × Solvent × Acid | ≥1 well ≥30%: fix PC+Solvent, go to Round 2 |
| 2 (if hit) | 24 wells | Acid stoich (0.5–3 equiv), NHP equiv (1.0–2.5), PC loading (1–5 mol%) — RSM/CCD | ≥60%: scale up |
| 3 (if needed) | 24 wells | Temperature (rt, 40, 60°C), time (8, 16, 24 h) | ≥60%: scale up |

**Bayesian BO vs. full factorial:**
The 24-condition search space equals the plate — BO offers no advantage in Round 1.
BO is beneficial from Round 2 onward when continuous variables expand the search space
beyond plate capacity (e.g. 5 acid equiv × 3 NHP equiv × 4 PC loadings × 3 temperatures = 180 points).

## Reagents to purchase

| Reagent | Priority | Reason |
|---------|----------|--------|
| **TFA (trifluoroacetic acid)** | **Essential** | Only Brønsted acid needed; absent from all 74 kit entries |
| Acetic acid / p-TsOH | High | Alternative mild acids to sweep acid-strength effect in Round 2 |
| K₂HPO₄ / NaH₂PO₄ buffer | Medium | Aqueous-acid conditions increasingly used in Minisci; Water (kit #73) present but no buffer |
| [Ir(dFppy)₂(bpy)]PF₆ | Medium | Intermediate E* between rows C and D; completes the Ir E* series |
| Thiophenol (PhSH) | Low | HAT catalyst for challenging Minisci; entirely absent |

## Audit
- Design: 4×3×2 = 24 ✓; df: 3+2+1+6+3+2+6 = 23 ✓
- All 4 PCs have E* more negative than −0.89 V; all can potentially reduce NHP ester
- Row A (Ir(ppy)₃, E* = −1.51 V) is the most likely to succeed; acts as positive reference
- Row D (E* = −0.89 V) is the borderline test; if Row D fails while Row A succeeds, confirms E* threshold
- Odd/even pairing of acid ensures acid effect is estimable across all PC/Solvent combos
- Dispensing randomised, seed = 7; sequence recorded in `009_design_definition.py`
"""

with open('phase_01_minisci_reagent_inventory.md', 'w') as f:
    f.write(phase1_text)
with open('phase_02_minisci_campaign_design.md', 'w') as f:
    f.write(phase2_text)
print("Phase documents written.")
