
import os, re

MD = '/home/ubuntu/rayca-sessions/d5c028fb-e517-477c-b564-bddb7d31c1eb-396fce89620d/md_prep'
os.makedirs(f'{MD}/inputs', exist_ok=True)

cpd_ids = ['EDS00495858','EDS00480994','EDS00444974','EDS00481054','EDS00441134','EDS00445742']
cpd_class = {'EDS00495858':'active','EDS00480994':'active','EDS00444974':'active',
             'EDS00481054':'inactive','EDS00441134':'inactive','EDS00445742':'inactive'}

def extract_lig_top(top_path):
    """Return (atomtypes_block, molecule_block) from acpype .top file."""
    text = open(top_path).read()
    # atomtypes section
    at_match = re.search(r'\[ atomtypes \].*?(?=\[ moleculetype \])', text, re.DOTALL)
    atomtypes = at_match.group(0).strip() if at_match else ''
    # everything from [ moleculetype ] onwards
    mol_match = re.search(r'(\[ moleculetype \].*)', text, re.DOTALL)
    mol_block = mol_match.group(1).strip() if mol_match else ''
    return atomtypes, mol_block

for cid in cpd_ids:
    top_path = f'{MD}/{cid}_gmx/{cid}.amb2gmx/{cid}_GMX.top'
    gro_path = f'{MD}/{cid}_gmx/{cid}.amb2gmx/{cid}_GMX.gro'
    
    atomtypes, mol_block = extract_lig_top(top_path)
    
    # Write ligand .itp (molecule definition only — includes atomtypes + molecule)
    itp_path = f'{MD}/inputs/{cid}.itp'
    with open(itp_path, 'w') as f:
        f.write(f'; Ligand topology for {cid} — GAFF2+Gasteiger, generated by acpype\n')
        f.write(f'; Charge method: Gasteiger (qualitative pilot comparison)\n\n')
        f.write(atomtypes + '\n\n')
        f.write(mol_block + '\n')
    
    # Copy ligand .gro
    os.system(f'cp {gro_path} {MD}/inputs/{cid}.gro')
    
    n_atoms = sum(1 for l in open(gro_path) if l.startswith(' ') and len(l.split()) >= 8)
    print(f'{cid} ({cpd_class[cid]}): itp written ({len(mol_block)} chars), {n_atoms} atoms in gro')

print('\nLigand itp + gro files ready in md_prep/inputs/')
